hurricane:
  data_path: /lustre/blue2/ranka/eklasky/software_X_data/data/Hurricane_Isabel.bp
  # Reads all 19 float fields, sorted by variable name, into RAM.
  train_subset:
    variable_idx: null
    section_range: [0, 1]
    frame_range: [0, 100]
  test_subset:
    variable_idx: null
    section_range: [0, 1]
    frame_range: [0, 100]
train_config:
  augment_type: {}
  inst_norm: true
  n_frame: 16
  n_overlap: 0
  norm_type: mean_range
  train: true
  train_size: 256
test_config:
  augment_type: {}
  inst_norm: true
  n_frame: 16
  n_overlap: 0
  norm_type: mean_range
  test_size: [256, 256]
  train: false
